config/routes.rb
Banking::Application.routes.draw do
  root :to => "users#transfer"

  match "/login", :to => "users#login"
  match "/transfer", :to => "users#transfer"
  get "/logout", :to => "users#logout"

end

app/models/transfer_log.rb
class TransferLog < ActiveRecord::Base
	#Sender transfers to recipient
	belongs_to :sender, :class_name => "User" #Sending end of the transfer
	belongs_to :recipient, :class_name => "User" #Receiving end of the transfer

	attr_accessible :amount, :sender_id, :recipient_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :debit_logs, :class_name => "TransferLog", :foreign_key => "sender_id" #Logs for my outgoing transactions
  has_many :credit_logs, :class_name => "TransferLog", :foreign_key => "recipient_id" #Logs for my incoming transactions

  attr_accessible :username, :password
  attr_accessor :password
  attr_protected :id, :salt

  validates_presence_of :username, :message => "^Hast thou not been given a name?"
  validates_presence_of :encrypted_password, :balance, :salt
  validates_uniqueness_of :username
  validates_numericality_of :balance
  validate :balance => {:greater_than_or_equal_to => 0}

  before_validation :set_default_balance

  def transfer(recipient_username, amount)
  	amount = amount.to_f.to_d #Make sure amount is a real number
  	if (recipient = User.where(:username => recipient_username).first) && amount > 0 && self.balance - amount >= 0 #User exists, transfers a positive amount, and has money
  		self.balance = self.balance - amount
  		recipient.balance = recipient.balance + amount
  		#Build a log entry of the performed transfer, as a debit for me.
  		debit_log = self.debit_logs.new(:recipient_id => recipient.id, :amount => amount)

  		self.transaction do #Perform transactions simultaneously to prevent errors from stopping the transaction halfway through
  			self.save!
  			recipient.save!
  			debit_log.save!
  		end
  	else
  		false
  	end
  end

  def self.authenticate(username, password)
    #Does user exist? And if so, is password correct?
    if !(user = User.where(:username => username).first).nil? && user.encrypted_password == Digest::SHA512.hexdigest(password+user.salt).to_s
      user
    else
      false
    end
  end

  def password=(pass)
    if pass
      self.salt ||= SecureRandom.hex(16) #random string
      self.encrypted_password = Digest::SHA512.hexdigest(pass+self.salt).to_s
    else
      raise "Thou shalt secure thy account with a password"
    end
  end

  private

  def set_default_balance
    self.balance ||= 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery

	def authenticate
	    if session[:user]
	      return true
	    end
	    flash[:warning] = 'Thou shalt authenticate!'
	    redirect_to :controller => "users", :action => "login"
	    return false 
	end

	def current_user
    	session[:user]
  	end	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate, :except => [:login]

	def login
		if request.post? #In the simple case of this app, route get and post through the same controller action to keep the code clean
		    if session[:user] = User.authenticate(params[:user][:username], params[:user][:password])
		        flash[:message]  = "Welcome, my child."
		        redirect_to :transfer
		    else
		        flash[:warning] = "Thou shall not pass!"
		    end
		end
	end

	def logout
	    session[:user] = nil
	    flash[:message] = 'Thou shalt return!'
	    redirect_to :login
  	end

  	def transfer
		if request.post? #In the simple case of this app, route get and post through the same controller action to keep the code clean
			if current_user.transfer(params[:recipient][:username], params[:recipient][:amount].to_d)
				flash[:message] = (params[:recipient][:amount]).to_s + " transferred to " + params[:recipient][:username]
		  		redirect_to :transfer
			else
		  		flash[:warning] = "Thou shalt not perform an invalid transfer!"
		  		redirect_to :transfer
			end
		elsif request.get?
			@recipients = User.all(:conditions => (current_user ? ["id != ?", current_user.id] : [])) #Get all possible users to transfer money to, thus excluding myself
			@current_user = current_user
			#Get all my transfer logs (incoming and outgoing) and order them by date
			@transfer_logs = @current_user.debit_logs + @current_user.credit_logs
			@transfer_logs.sort_by!(&:created_at).reverse!
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Banking</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
	<div><p><%= value %></p></div>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/login.html.erb
<h1>Login</h1>
<%= form_for :user, :controller => :users, :action => :login, :method => :post do |f| %>
	<%= f.text_field :username, :placeholder => "User name" %><br>
	<%= f.password_field :password, :placeholder => "Password" %><br>
	<%= f.submit "Login" %>
<% end %>

app/views/users/transfer.html.erb
<%= link_to "Logout", logout_url %>
<h1>Banking</h1>
<h2>Balance <%= number_to_currency(@current_user.balance) %></h2>

<%= form_for :recipient, :controller => :users, :action => :transfer, :method => :post do |f| %>
	<%= f.text_field :amount, :placeholder => "Amount" %><br>
	<%= f.select(:username, @recipients.map{|r| r.username}, :prompt => "Select recipient") %><br>
	<%= f.submit "Transfer" %>
<% end %>

<hr>
<h2>History</h2>
<table id="history">
	<thead>
		<tr>
			<th>Date</th>
			<th>Sender</th>
			<th>Recipient</th>
			<th>Amount</th>
		</tr>
	</thead>
	<tbody>
		<% @transfer_logs.each do |transfer| %>
			<tr>
				<td><%= transfer.created_at %></td>
				<td><%= transfer.sender.username %></td>
				<td><%= transfer.recipient.username %></td>
				<td><%= number_to_currency(transfer.amount) %></td>
			</tr>
		<% end %>
	</tbody>
</table>